name: Update Border Queue Data

on:
  schedule:
   - cron: '45 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Minsk' # 👈 Принудительно ставим белорусское время!
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run updater script
      run: python gpk_updater.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add gpk_real_archive.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Автообновление данных очереди"
        git push
